### ISSUE TITLE
Overwrite option has no effect

### ISSUE THREAD

**Issue by timkelty** [enl/flysystem-cloudinary#25]
Thanks so much for this library!

Working great for me, except `overwrite` seems to have no effect.

I can upload, copy, move, and delete fine regardless of the setting.

However, If I try to upload a file that exists in Cloudinary (even with overwrite: true), I get a `FileExistsException` thrown by assertAbsent: https://github.com/thephpleague/flysystem/blob/master/src/Filesystem.php#L82

Any ideas?

**Comment by enl** [comment]
Hello, you need to use this option for Filesystem class configuration in order to bypass its asserts:

```php
$filesystem = new Filesystem($adapter, ['disable_asserts' => true]);
```

I've updated the documentation in 1.1 branch.

**Comment by timkelty** [comment]
@enl got it, thanks.

So…I'm still a bit confused what the `overwrite` option in the `Enl\Flysystem\Cloudinary::configure` _should_ do…or will that be removed in 1.1? I see you've added it as an option for `[Enl\Flysystem\Cloudinary ::upload](https://github.com/enl/flysystem-cloudinary/blob/release/1.1/src/ApiFacade.php#L50-L60)`, but not sure how that relates to the client config.

**Comment by enl** [comment]
@timkelty Looks like I was a bit confused too when I did it. There is `overwrite` option for Cloudinary API client. It is used to define whether Cloudinary should overwrite the file. It can be set per client (with `\Cloudinary::config($options)` or per request (with `Uploader::upload(new DataUri($contents), $options)`).

BTW, looks like I confused myself with this changes, it is not needed, since Filesystem does not allow to configure this per request.

**Comment by enl** [comment]
As for now, `overwrite` option is only passed to `Cloudinary::configure` on Api facade constructor.

`overwrite` parameter was introduced (yes, again) for `ApiFacade::upload` method:
`CloudinaryAdapter::update` sets it to `true`, but `CloudinaryAdapter::write`
uses `disable_asserts` Flysystem value for this parameter.

BTW, it looks like `overwrite` option does not work in Cloudinary API at all.
